<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name on Card_name_on_card</name>
   <tag></tag>
   <elementGuidId>395f7a8b-2120-4479-84e8-25513a0c292e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name_on_card&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name_on_card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7bcda9b-3eab-4e8c-8f9d-f00c19fe4b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3a5259a-3b04-4a9b-b1ed-d87aeaa537e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name_on_card</value>
      <webElementGuid>385ad6db-67cb-44ca-be80-fb0dbd4fa418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>name-on-card</value>
      <webElementGuid>8a9caca8-4a91-46ed-b652-a1932e237054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b233176-42fb-4bb9-a915-acba4f802be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-12 form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>b0c31fa4-69a2-412b-b5a8-034b4e88078f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name_on_card']</value>
      <webElementGuid>c07dd7da-d7ad-46cd-83c8-ada4ae0235c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div/div/input</value>
      <webElementGuid>d4cfa5c6-7e62-49d3-b378-fc909a3b05f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8da75e68-5574-4dd5-bae0-e3ce4d55a532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name_on_card' and @type = 'text']</value>
      <webElementGuid>a7ed6d1c-7e5d-4170-95fa-54472933eee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
