<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number_card_number</name>
   <tag></tag>
   <elementGuidId>e8ce9533-0505-4c38-9394-d77ec8b28fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;card_number&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='card_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5ab99fe-5a17-40cd-b6e1-c47888d0637d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>74e3cc21-26ba-4b2e-85e9-96cc5bd04c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>card-number</value>
      <webElementGuid>c35aace9-22a4-4908-a9fa-1339505d154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control card-number</value>
      <webElementGuid>d8cb0337-16f7-4b78-8385-7c56ee69dcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d04ff042-7024-4e5c-b7c8-376396794eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-12 form-group card&quot;]/input[@class=&quot;form-control card-number&quot;]</value>
      <webElementGuid>d5375b86-54fe-43d3-8d57-d2f7dd4b6d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='card_number']</value>
      <webElementGuid>996e8a90-e41d-4b94-a9bc-29bb4989ef70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div[2]/div/input</value>
      <webElementGuid>dc2e7ee6-3f4c-485b-afb6-87f7f438319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9b4f922a-344a-4b1e-bb1e-a8c52214ac89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'card_number' and @type = 'text']</value>
      <webElementGuid>ffaedf4f-73ff-4e1b-bc1c-d1a62511dc2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
