<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close</name>
   <tag></tag>
   <elementGuidId>45cebeff-cb05-4467-8c87-592951ddfb64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ns-nyr4h-e-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>80b49c43-0cc5-4d70-bea7-7c1a1f5a6e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-nyr4h-e-18</value>
      <webElementGuid>100d25c2-4a00-41f0-85ab-b52104e1ea43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3df7d343-d3fd-4cd0-875b-f50af2efa1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-ns-nyr4h-e</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>9b565ad1-7bd7-408a-bd3f-9cfaf8e01a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-score</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d71cb064-0166-4b92-92bf-f75b3b64daa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>981371f5-529b-4485-aa82-fea497d05003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)/div[@class=&quot;ns-nyr4h-e-17&quot;]/span[@class=&quot;ns-nyr4h-e-18&quot;]</value>
      <webElementGuid>e8e56b84-3c5b-4c26-9469-631487075be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Automation Exercise/iframe_Ad_ad_iframe</value>
      <webElementGuid>438402dd-7d92-424d-985f-ddd562c754f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']/div/span</value>
      <webElementGuid>7daa2cc0-fc77-4da9-9598-efeeb56e77ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='convex.dev'])[1]/following::span[1]</value>
      <webElementGuid>c8e46071-03e3-4e1c-a0c0-d3aa9e230f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fully relational, super easy to use. Get started in fiveminutes.'])[1]/following::span[1]</value>
      <webElementGuid>8b160d5e-367b-4412-80cb-0806007991c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::span[1]</value>
      <webElementGuid>9704cdf6-32cb-474f-9626-992e0a26cc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>4677699b-707d-450a-81f3-29bec01b0749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>79a24702-fd6a-4b4f-8ea3-9305a92b9db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>14eb007a-e52c-4996-a04d-dfdff79cf100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
