<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Men Tshirt</name>
   <tag></tag>
   <elementGuidId>d460d5b9-ec6a-4f6b-8a05-8bdd9d3b959d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-2']/td[2]/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>290371da-7b0e-444c-acf3-226b2a202196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product_details/2</value>
      <webElementGuid>22390926-1b7a-46bb-ae35-01db26e2d83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men Tshirt</value>
      <webElementGuid>4e55ad44-e1c4-4c8a-a80e-4790ea3fd21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-2&quot;)/td[@class=&quot;cart_description&quot;]/h4[1]/a[1]</value>
      <webElementGuid>0aef2ef9-4d20-4972-8d74-600804ac7ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-2']/td[2]/h4/a</value>
      <webElementGuid>16a4a092-85db-46ef-86bf-4a63a275016f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Men Tshirt')]</value>
      <webElementGuid>62229a70-3eb7-4cd3-aad5-62e123bd8a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[2]</value>
      <webElementGuid>4d3edbbe-c171-4fda-b734-b176ef79ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::a[2]</value>
      <webElementGuid>0a5684b7-e416-41da-a864-ae3b12bbb0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pure Cotton V-Neck T-Shirt'])[1]/preceding::a[3]</value>
      <webElementGuid>e35833ef-5ed0-4b78-b3a9-4da9270537c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::a[5]</value>
      <webElementGuid>76328d83-0bf9-4a10-949a-3690000dc89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Men Tshirt']/parent::*</value>
      <webElementGuid>4564d9c7-2bdb-4ff1-aff1-72df1e17f4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product_details/2')]</value>
      <webElementGuid>390ec5fe-91f3-443f-974f-ce355e1f3cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>f4f23163-763c-486c-9830-ae7651638a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product_details/2' and (text() = 'Men Tshirt' or . = 'Men Tshirt')]</value>
      <webElementGuid>efd11801-cf4d-49e8-a5a1-3dc3474100b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
