<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pure Cotton V-Neck T-Shirt</name>
   <tag></tag>
   <elementGuidId>04ae0841-1d99-4410-b983-03c9ba4f389f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-28']/td[2]/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-28 > td.cart_description > h4 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e869d47d-95d1-4e70-95c3-1b1049828a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product_details/28</value>
      <webElementGuid>370f134f-beb3-49e5-beb7-8f1e7fcee0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pure Cotton V-Neck T-Shirt</value>
      <webElementGuid>d78d3965-7b13-4d2b-b665-e555e200515a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-28&quot;)/td[@class=&quot;cart_description&quot;]/h4[1]/a[1]</value>
      <webElementGuid>0292eb07-0c02-4a8e-acb4-2a49ea5209b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-28']/td[2]/h4/a</value>
      <webElementGuid>279919a1-60e2-4281-b8a4-2f82e7c4852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pure Cotton V-Neck T-Shirt')]</value>
      <webElementGuid>88a165cf-e449-4bf9-b34a-1c771f79698e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/following::a[3]</value>
      <webElementGuid>a5b9c284-013b-440a-8f46-d4a1a48cd92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[5]</value>
      <webElementGuid>aa50afbf-b7f8-4f18-b48a-a8952e32effb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::a[2]</value>
      <webElementGuid>aa5b4eec-d7a6-46a8-a02d-71c307354cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/preceding::a[2]</value>
      <webElementGuid>aef1a55f-0446-478c-bb2a-a2937909ca80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pure Cotton V-Neck T-Shirt']/parent::*</value>
      <webElementGuid>64b9e5ef-6beb-4689-bab1-e2841021cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product_details/28')]</value>
      <webElementGuid>bc238a68-631a-467e-8497-161e2fd6001a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/h4/a</value>
      <webElementGuid>76195ffe-2caf-46f0-b2fd-5cdcea013f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product_details/28' and (text() = 'Pure Cotton V-Neck T-Shirt' or . = 'Pure Cotton V-Neck T-Shirt')]</value>
      <webElementGuid>409ef543-2779-478e-acaf-3796f7537c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
