<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pure Cotton V-Neck T-Shirt (1)</name>
   <tag></tag>
   <elementGuidId>ac76a1df-9604-4bf6-874d-e2108985245f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-28']/td[2]/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-28 > td.cart_description > h4 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>820083dc-4814-4bfa-8eea-7984d7d5f2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product_details/28</value>
      <webElementGuid>79dc42bf-e2f1-49b2-a654-8f2ffc1ee82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pure Cotton V-Neck T-Shirt</value>
      <webElementGuid>77650cc1-2d97-4871-a0d9-447c8b11c6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-28&quot;)/td[@class=&quot;cart_description&quot;]/h4[1]/a[1]</value>
      <webElementGuid>0e5aa2f7-d933-4e47-bb57-708a4fa65ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-28']/td[2]/h4/a</value>
      <webElementGuid>3f086001-b31a-434e-8c95-bf10450388c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pure Cotton V-Neck T-Shirt')]</value>
      <webElementGuid>08b16e8e-aea1-4537-9d94-d08fc3adb3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/following::a[3]</value>
      <webElementGuid>eb15592b-a1eb-4f82-b9b2-8a0f538abe18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[5]</value>
      <webElementGuid>ce476f6e-703d-4f2b-bad2-927c55296e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::a[2]</value>
      <webElementGuid>7dd5184c-c58c-41a2-8f66-e302d621bd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/preceding::a[2]</value>
      <webElementGuid>f8e502c5-7d9e-441f-9a20-6c1d9909213e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pure Cotton V-Neck T-Shirt']/parent::*</value>
      <webElementGuid>8f4fc22e-6109-4e42-89ff-4c0afdc3e39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product_details/28')]</value>
      <webElementGuid>73befc3d-679b-4781-8307-020c0b6b18fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/h4/a</value>
      <webElementGuid>e0456854-9a70-4160-aa91-0954d1001c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product_details/28' and (text() = 'Pure Cotton V-Neck T-Shirt' or . = 'Pure Cotton V-Neck T-Shirt')]</value>
      <webElementGuid>f79e2b71-4a34-4fce-9bc2-83a8374a6f28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
