<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Pure Cotton V-Neck T-Shirt_fa fa-times</name>
   <tag></tag>
   <elementGuidId>c5e89f9e-7240-459b-bea8-9aaf801781e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-28 > td.cart_delete > a.cart_quantity_delete > i.fa.fa-times</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-28']/td[6]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>62a0dddf-a64c-4ee0-9193-324d42a42f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>82083467-190a-4128-b528-25d5e68775ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-28&quot;)/td[@class=&quot;cart_delete&quot;]/a[@class=&quot;cart_quantity_delete&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>ad7a5e09-eec0-41f2-8c0e-b67e94e46ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-28']/td[6]/a/i</value>
      <webElementGuid>1359aa81-ab12-4d21-8e35-68370f1ad4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/a/i</value>
      <webElementGuid>2ea85029-5f5d-4085-9e82-be620ceed764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
